on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_first_time_setup:
    name: MacOS with Docker
    runs-on: macos-15-intel
    if: "!contains(github.event.pull_request.labels.*.name, 'bypass-ci')"
    steps:
      - name: Install dependencies
        run: brew install caddy sqlite3

      - name: Install Docker
        run: |
          brew install colima docker
          brew services start colima
          colima start

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run first time setup
        run: |
          cp .env.ci .env
          npm install
          node set-env DOCKER_EXECUTABLE docker
          node setup --no-auth --no-tls
          rm .finish-setup

      - name: Run tests
        run: npm test
